version: "2"

services:
    web:
        image: node:8.11
        ports:
          - "3001:3000"
        volumes:
          - "./:/app"
        working_dir: /app
        command: bash -c "yarn install; yarn start;"
    server:
        image: php:7.2-apache
        ports:
          - "8000:80"
        volumes:
          - "./importer:/var/www/html"
